### PR TITLE
Update core-foundation-sys to 0.8

### PR DESCRIPTION
**Pull request by jrmuizel**

### CODE REVIEW

**Comment by ChunMinChang** [comment]
Why? Is this for updating `core-foundation-sys` in gecko?

**Comment by jrmuizel** [comment]
Yes

**Comment by jrmuizel** [comment]
Otherwise we end up with multiple copies

**Comment by ChunMinChang** [comment]
Can you paste the bug number here?

**Comment by jrmuizel** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1654699

**Pull request merged**
