### PR TITLE
Remove panning utilities from cubeb

### PR DESCRIPTION
**Pull request by padenot**

### CODE REVIEW

**Comment by padenot** [comment]
See https://github.com/kinetiknz/cubeb/pull/532.

**Comment by padenot** [comment]
As noted on IRC, this will fail until `cubeb-backend` has a new version.

**Comment by ChunMinChang** [comment]
I'll wait until https://github.com/djg/cubeb-rs/pull/44 is merged.

**Comment by kinetiknz** [comment]
cubeb-rs 0.6.0 is published with these changes now.

**Comment by ChunMinChang** [comment]
@padenot : Could you update the `cubeb-backend` to 0.6 so that we can pass the tests.

**Review by ChunMinChang — APPROVED** [review]
LGTM!

**Comment by ChunMinChang** [comment]
The change is to meet https://github.com/kinetiknz/cubeb/pull/532. Add a reference from here so [BMO 1575638](https://bugzilla.mozilla.org/show_bug.cgi?id=1575638) is able to track the corresponding changes.

**Comment by ChunMinChang** [comment]
> The change is to meet [kinetiknz/cubeb#532](https://github.com/kinetiknz/cubeb/pull/532). Add a reference from here so [BMO 1575638](https://bugzilla.mozilla.org/show_bug.cgi?id=1575638) is able to track the corresponding changes.

Oops we already have one in https://github.com/ChunMinChang/cubeb-coreaudio-rs/pull/10#issuecomment-523521805

**Pull request merged**
